name: Deploy Storybook to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Install dependencies
        run: npm install
        working-directory: packages/docs

      - name: List files in react package
        run: ls -la packages/react/src/components/


      - name: Build Storybook
        run: npx turbo run build
        # run: npm run build
        # working-directory: packages/docs
        env: 
          TURBO_TOKEN: n1Y3hfCzYGthUJAdV8JYocWb
          TURBO_TEAM: luandersonh's projects

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: packages/docs/storybook-static
